---
ID: "c7427508-7057-4bf4-b2f5-ac14ce0ca9c3"
Parent: "10c1c247-49c5-4c15-a5c6-ab56854ff5a6"
Template: "10c1c247-49c5-4c15-a5c6-ab56854ff5a6"
Path: /sitecore/templates/Data Exchange/Providers/Xml/Folders/Xml Tenant Settings Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180626T071659Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
