---
ID: "943b8798-6781-44ec-ae8f-1df2f016e571"
Parent: "1369eca1-f066-44ab-a8fd-8209a8a1becf"
Template: "1369eca1-f066-44ab-a8fd-8209a8a1becf"
Path: /sitecore/templates/Data Exchange/Providers/Xml/Folders/Xml Mappings Applied Actions Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180626T071658Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
