---
ID: "0b491a22-e31a-40bb-ae80-4f96a48e564a"
Parent: "2630f815-2ae9-4fc5-a694-2073367608f0"
Template: "2630f815-2ae9-4fc5-a694-2073367608f0"
Path: /sitecore/templates/Data Exchange/Providers/Xml/Folders/Xml Mappings Applied Action Rules Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180626T071658Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
