---
ID: "c4a082fa-fdb0-4541-8a34-de23cfe960b5"
Parent: "68883f7b-e960-4733-b3ed-d1508eb341e9"
Template: "b2613cc1-a748-46a3-a0db-3774574bd339"
Path: /sitecore/templates/Branches/Data Exchange/Providers/Xml/Commands/Xml Tenant Settings
DB: master
BranchID: "d1dcfbcc-dacc-414f-bdc4-8a3e1c41988b"
SharedFields:
- ID: "854cc8f6-94ad-4521-a4b6-44ed8f794c98"
  Hint: Command
  Value: "dataExchange:createItemWithoutPromptingForNameCommand(settingsItem={C4A082FA-FDB0-4541-8A34-DE23CFE960B5})"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 2000
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{BF1E390B-56CA-45AF-ACA0-58627A659C9D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180626T071700Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
