---
ID: "e0eb1922-af55-4802-afa6-68accbfe0ae7"
Parent: "c2256ce8-d5a2-48ed-a075-aef18e4acd82"
Template: "c2256ce8-d5a2-48ed-a075-aef18e4acd82"
Path: /sitecore/templates/Data Exchange/Providers/Xml/Folders/Xml Filter Expressions Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180626T071658Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
