---
ID: "9cb244b3-8160-4258-ac4e-d4ed03521d62"
Parent: "bd4e1eea-2223-4082-b3c7-c253d1099276"
Template: "bd4e1eea-2223-4082-b3c7-c253d1099276"
Path: /sitecore/templates/Data Exchange/Providers/Xml/Folders/Xml Value Accessors Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180626T071659Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
